version: '2'
services:
  web:
    build: ./web
    container_name: web
    ports:
      - "8888:5000"
    networks:
      mongo_net:
    depends_on:
      - mongo 
  mongo:
    build: ./mongo
    container_name: mongo
    networks:
      mongo_net:
 
networks:
  mongo_net:       
